<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Admin Auth Assignment' => '',
    'Administration module' => 'Модуль администрирования',
    'Auth Key' => '',
    'Item Names' => '',
    'Passhash' => '',
    'Provides administration panel functionality with backend user management' => '',
    'Record was successfully created' => 'Запись успешно создана',
    'Record was successfully deleted' => 'Запись успешно удалена',
    'Record was successfully updated' => 'Запись успешно обновлена',
    'Administration panel' => 'Панель администратора',
    'Administrator' => 'Администратор',
    'Administrators' => 'Администраторы',
    'All records' => 'Все записи',
    'Are you sure to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Are you sure to delete this items?' => 'Вы уверены, что хотите удалить эти элементы?',
    'Create' => 'Создать',
    'Create & Exit' => 'Создать и выйти',
    'Create & Then Create Another One' => 'Создать, а затем создать еще одну запись',
    'Create Time' => 'Дата создания',
    'Create with default parameters' => 'Создать с параметрами по-умолчанию',
    'Create {item}' => 'Создать {item}',
    'Delete' => 'Удалить',
    'Delete Checked' => 'Удалить отмеченные',
    'Edit' => 'Изменить',
    'Email' => 'Email',
    'Go Back' => 'Вернуться назад',
    'Groups' => 'Группы',
    'ID' => 'ID',
    'Incorrect login or password' => 'Неправильный логин или пароль',
    'Is Active' => 'Активен',
    'Is Super Admin' => 'Супер администратор',
    'List' => 'Список',
    'Login' => 'Логин',
    'Login Time' => 'Время последнего захода',
    'Logout' => 'Выйти',
    'Name' => 'Имя',
    'No' => 'Нет',
    'Password' => 'Пароль',
    'Search' => 'Поиск',
    'Sign in' => 'Войти',
    'Update' => 'Сохранить',
    'Update & Exit' => 'Сохранить и выйти',
    'Update Time' => 'Дата обновления',
    'Update {item}: {title}' => 'Обновить {item}: {title}',
    'View' => 'Просмотр',
    'Yes' => 'Да',
    'You do not have access to the requested operation' => 'У вас нет доступа к запрошенной операции.',
    'Your profile' => 'Ваш профиль',
);
