<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Search' => 'Поиск',
  'Administration panel' => 'Панель администратора',
  'Administrator' => 'Администратор',
  'Administrators' => 'Администраторы',
  'Create' => 'Создать',
  'Create & Exit' => 'Создать и выйти',
  'Create {item}' => 'Создать {item}',
  'Delete Checked' => 'Удалить отмеченные',
  'Edit' => 'Изменить',
  'Go Back' => 'Вернуться назад',
  'Groups' => 'Группы',
  'Incorrect login or password' => 'Неправильный логин или пароль',
  'List' => 'Список',
  'Login' => 'Логин',
  'Logout' => 'Выйти',
  'Password' => 'Пароль',
  'Sign in' => 'Войти',
  'Update' => 'Сохранить',
  'Update & Exit' => 'Сохранить и выйти',
  'Update {item}: {title}' => 'Обновить {item}: {title}',
  'You do not have access to the requested operation' => 'У вас нет доступа к запрошенной операции.',
  'Your profile' => 'Ваш профиль',
);
